### ISSUE TITLE
x64 plugin release

### ISSUE THREAD

**Issue by chcg** [gallettube/MusicPlayer#2]
Hi, are you planning to do a release for x64 of the plugin?

**Comment by gallettube** [comment]
Hi, I didn't think about it but If you want just give me the dll and I'll update it.
You can contact me at jongalletero @ gmail.com
Thanks for your pull request

**Comment by chcg** [comment]
@gallettube 
See e.g. https://ci.appveyor.com/project/chcg/musicplayer/build/1.0.11 the build artifacts are available there for x86 and x64 release builds, see:
https://ci.appveyor.com/project/chcg/musicplayer/build/1.0.11/job/y4hae49mpvkxogfu/artifacts
https://ci.appveyor.com/project/chcg/musicplayer/build/1.0.11/job/50el3n6a1odus2il/artifacts

I could also create a tag in my repo so some zipfiles by appveyor are created as release action, if you like.

**Comment by gallettube** [comment]
Yeah I would appreciate it, I don't have windows anymore so I can't compile.
But I saw that the latest version you create is 1.0.12  if you give me the binary file to any cpu I will upload to the plugin manager console.

**Comment by chcg** [comment]
You could register your project at https://www.appveyor.com/, if you like. It's free for open source projects and provides a Windows build service.
See https://stackoverflow.com/questions/516730/what-does-the-visual-studio-any-cpu-target-mean. As notepad++ is a native application the plugin dll has to match to the installed n++ version. It is possible to run the 32bit n++ on windows 64bit in this case the anycpu dll would not match.
So two versions of the plugin are needed.

**Comment by gallettube** [comment]
Ok I will so you mean if there is a notepad++ 64 bits can't run a 32 bits
one?
I don't know if in the plugin manager console I've the option to upload
both versions I'll try to put both of the version 1.0.11
I'll let you know
Thanks for info ;)

Best Regards / Saludos,

Jon Galletero

2018-02-02 22:27 GMT+01:00 chcg <notifications@github.com>:

**Comment by chcg** [comment]
@gallettube 
See https://github.com/bruderstein/npp-plugins-x64, there is no integrated webinterface which contains the PM list for 32bit and 64bit plugins yet. 
The version1.0.11 is just the build version of appveyor. For the PluginManager relevant is the version reported by the dll, see https://github.com/gallettube/MusicPlayer/blob/master/MusicPlayer/Properties/AssemblyInfo.cs and that one is still 1.0.0.3.

See also my testbuild with tagging 1.0.0.3.16
https://ci.appveyor.com/project/chcg/musicplayer/build/1.0.0.3.16
with deployment to
https://github.com/chcg/MusicPlayer/releases/tag/1.0.0.3.16

**Comment by gallettube** [comment]
Is because I submmited in the plugin manager admin console and spend time
since the manager update it.
In sourceforge I create a release days ago and now I've created a release
with the binaries:
https://github.com/gallettube/MusicPlayer/releases

Thanks for help!

2018-02-04 9:21 GMT+01:00 chcg <notifications@github.com>:

**Comment by chcg** [comment]
@gallettube Could you add the x64 version also as zip file. PM just can handle zip files as input, but not plain dlls.

**Comment by gallettube** [comment]
Done ;)

Best Regards / Saludos,

Jon Galletero

2018-02-04 11:42 GMT+01:00 chcg <notifications@github.com>:

**Comment by chcg** [comment]
Added to the PM x64 list https://github.com/bruderstein/npp-plugins-x64/commit/ec2cfe77411dfcaf389f17bbfb9d2229655a0860
